
[package]
name = "lost_ray"
version = "0.1.0"
authors = ["LostRay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
rand = "0.7.3"